import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Checkbox, Form, Input } from "antd";
import { GoogleLogin } from "@react-oauth/google";

export default function Home() {
  const onFinish = (values: any) => {
    console.log("Success:", values);
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  const responseGoogle = (response: any) => {
    console.log(response);
  };

  // useGoogleOneTapLogin({
  //   onSuccess: (credentialResponse) => {
  //     console.log(credentialResponse);
  //   },
  //   onError: () => {
  //     console.log("Login Failed");
  //   },
  // });

  return (
    <>
      <Head>
        <title>Google One Tap Authentication Testing App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2
          style={{
            marginBottom: 50,
            fontFamily: "sans-serif",
          }}
        >
          Welcome To Join Mudassir Dev...!
        </h2>
        <Form
          name="basic"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          initialValues={{ remember: true }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[{ required: true, message: "Please input your username!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: "Please input your password!" }]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item
            name="remember"
            valuePropName="checked"
            wrapperCol={{ offset: 8, span: 16 }}
          >
            <Checkbox>Remember me</Checkbox>
          </Form.Item>

          <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
            <Button type="primary" htmlType="submit">
              Login with Email
            </Button>
          </Form.Item>
        </Form>
        <div style={{ display: "flex" }}>
          <GoogleLogin
            onSuccess={(credentialResponse) => {
              console.log(credentialResponse);
            }}
            onError={() => {
              console.log("Login Failed");
            }}
            useOneTap
          />

          {/* <GoogleLogin
            clientId="300966724203-9e64cote67b4fosd50iis8jlpas6lp1h.apps.googleusercontent.com"
            buttonText="Continue with google"
            onSuccess={(googleReponse) => {
              responseGoogle(googleReponse);
            }}
            // render={(renderProps) => (
            //   <Button
            //     onClick={renderProps.onClick}
            //     type="default"
            //     htmlType="submit"
            //     style={{ marginTop: 10 }}
            //   >
            //     Signup with Google
            //   </Button>
            // )}
            style={{ marginTop: 10 }}
            onFailure={(googleReponse) =>
              console.log("googleReponse", googleReponse)
            }
            cookiePolicy={"single_host_origin"}
          /> */}
        </div>
      </main>
    </>
  );
}
